sudo: required
services:
  - docker

before_install:
  - docker build -t barefootjon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true barefootjon/docker-react npm run test

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "newapp"
  env: "Newapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-638821336320"
  bucket_path: "newapp"
  on:
    branch: master
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
